### ISSUE TITLE
Ability to start/end session outside opening/closing tab

### ISSUE THREAD

**Issue by dagingaa** [opentok/rtcstats-server#256]
We would love for there to be a way to start/end a session outside of opening and closing the tab. This is for example useful if you have a lot of back to back calls, and don't open a new browser window for every call. And if the user forgets to close the tab, we can end the session programatically and dump it to rtcstats at the logical end of the call, rather than closing the tab.

**Comment by fippo** [comment]
probably need to export the websocket from
https://github.com/opentok/rtcstats/blob/master/trace-ws.js
so it can be closed at the users discretion (which is the trigger for feature extraction)

**Comment by fippo** [comment]
btw: you don't need to call the wrap-function on page load, later is also ok. This solves the "connect when desired"

WRT closing I have a PR upcoming...
